tests = [{'description': 'PINA: 0x00 => PORC: 0x07',
    'steps': [ {'inputs': [('PINA',0x00)], 'iterations': 5 } ],
    'expected': [('PORTC',0x07)],
    },
    {'description': 'PINA: 0x02 => PORC: 0x06',
    'steps': [ {'inputs': [('PINA',0x02)], 'iterations': 5 } ],
    'expected': [('PORTC',0x06)],
    },
    {'description': 'PINA: 0x02 => PORC: 0x06',
    'steps': [ {'inputs': [('PINA',0x02)], 'iterations': 5 } ],
    'expected': [('PORTC',0x06)],
    },
    {'description': 'PINA: 0x01 => PORC: 0x07',
    'steps': [ {'inputs': [('PINA',0x01)], 'iterations': 5 } ],
    'expected': [('PORTC',0x07)],
    },
    {'description': 'PINA: 0x00 => PORC: 0x07',
    'steps': [ {'inputs': [('PINA',0x00)], 'iterations': 5 } ],
    'expected': [('PORTC',0x07)],
    },  
    {'description': 'PINA: 0x01 -> 0x03 => PORC: 0x00',
    'steps': [ {'inputs': [('PINA',0x01), ('PINA',0x03)], 'iterations': 5 } ],
    'expected': [('PORTC',0x00)],
    }, 
    ]


# {'description': 'PINA: 0x02 => PINA: 0x03 --> PORC: 0x00',
#     'steps': [ {'inputs': [('PINA',0x02)], 'iterations': 5 } ],
#     'expected': [('PORTC',0x00)],
#     }, 